"""UUIDv7 primary keys (RFC 9562).

Why UUIDs: public IDs that cannot be enumerated (`/posts/1`, `/posts/2`, ...)
and can be generated by any process without a database round trip.

Why version 7 (not 4): the first 48 bits are a millisecond timestamp, so new
IDs sort after old ones. Random v4 keys scatter inserts across the whole
B-tree index; v7 keys append near the end, like an auto-increment.

Python's `uuid.uuid7` arrives in 3.14; this is the same layout in a few lines.
IDs created within the same millisecond are not ordered among themselves, so
code that needs a strict order sorts by (created_at, id).
"""

import os
import time
import uuid


def uuid7() -> uuid.UUID:
    timestamp_ms = time.time_ns() // 1_000_000
    random_bits = int.from_bytes(os.urandom(10), "big")  # 80 bits
    value = ((timestamp_ms & 0xFFFF_FFFF_FFFF) << 80) | random_bits
    value = (value & ~(0xF << 76)) | (0x7 << 76)  # version 7
    value = (value & ~(0x3 << 62)) | (0x2 << 62)  # RFC 9562 variant
    return uuid.UUID(int=value)
