name: reference_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  cloud_firestore: ^6.10.0
  dio: ^5.11.1
  firebase_core: ^4.15.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_cloud_firestore: ^4.3.0

flutter:
  uses-material-design: true
