/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health/live': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Process is running.
     * @description Never checks dependencies — a failing database must not restart healthy processes.
     */
    get: operations['getLiveness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Process can serve traffic (dependencies reachable).
     * @description Checks hard dependencies (database, Redis), each with a timeout.
     *     503 means "stop routing traffic here", not "restart me". The body never
     *     contains error details because the endpoint is public.
     */
    get: operations['getReadiness'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/meta': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Public runtime configuration (API version, feature flags).
     * @description Lets clients adapt without a rebuild. Only flags declared public are
     *     listed; server-only flags never appear.
     */
    get: operations['getMeta'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description Stable, machine-readable error code. Clients switch on this, never on `title`/`detail`.
     * @enum {string}
     */
    ErrorCode:
      | 'bad_request'
      | 'validation_error'
      | 'authentication_error'
      | 'authorization_error'
      | 'not_found'
      | 'method_not_allowed'
      | 'not_acceptable'
      | 'conflict'
      | 'idempotency_key_reused'
      | 'unsupported_media_type'
      | 'rate_limited'
      | 'internal_error'
      | 'external_service_error';
    FieldError: {
      /** @description Dotted path to the field (`items.0.name`); null for errors not tied to one field. */
      field: string | null;
      /** @description Validator code, e.g. `required`, `max_length`, `invalid`. */
      code: string;
      message: string;
    };
    Problem: {
      /** Format: uri-reference */
      type: string;
      title: string;
      status: number;
      code: components['schemas']['ErrorCode'];
      detail?: string;
      instance?: string;
      request_id: string;
      errors?: components['schemas']['FieldError'][];
      /** @description Seconds until retrying is useful (only for `rate_limited`). */
      retry_after?: number;
    };
    Liveness: {
      /** @constant */
      status: 'ok';
    };
    Readiness: {
      /** @enum {string} */
      status: 'ok' | 'unavailable';
      /** @description One entry per dependency; values never include error details. */
      checks: {
        [key: string]: 'ok' | 'fail';
      };
    };
    Meta: {
      /** @constant */
      api_version: '1';
      /** @enum {string} */
      environment: 'development' | 'test' | 'staging' | 'production';
      /** @description Public feature flags. Server-only flags are never listed here. */
      features: {
        [key: string]: boolean;
      };
    };
  };
  responses: {
    /** @description Any error, as RFC 9457 Problem Details. */
    Problem: {
      headers: {
        'X-Request-ID': components['headers']['RequestId'];
        [name: string]: unknown;
      };
      content: {
        'application/problem+json': components['schemas']['Problem'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: {
    /** @description Correlation ID. Echoes a valid incoming `X-Request-ID`, otherwise generated. */
    RequestId: string;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getLiveness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Alive. */
      200: {
        headers: {
          'X-Request-ID': components['headers']['RequestId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Liveness'];
        };
      };
    };
  };
  getReadiness: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready. */
      200: {
        headers: {
          'X-Request-ID': components['headers']['RequestId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Readiness'];
        };
      };
      /** @description At least one dependency check failed. */
      503: {
        headers: {
          'X-Request-ID': components['headers']['RequestId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Readiness'];
        };
      };
    };
  };
  getMeta: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Client-visible configuration. */
      200: {
        headers: {
          'X-Request-ID': components['headers']['RequestId'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Meta'];
        };
      };
      default: components['responses']['Problem'];
    };
  };
}
