"""email optional, verification, firebase uid

Revision ID: 988a25c79aa3
Revises: 64f7d5eb9543
Create Date: 2026-10-03 10:54:12.846325

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "988a25c79aa3"
down_revision: str | Sequence[str] | None = "64f7d5eb9543"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("email_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column("users", sa.Column("firebase_uid", sa.String(length=128), nullable=True))
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=254), nullable=True)
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.create_unique_constraint(op.f("uq_users_firebase_uid"), "users", ["firebase_uid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_firebase_uid"), "users", type_="unique")
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("users", "email", existing_type=sa.VARCHAR(length=254), nullable=False)
    op.drop_column("users", "firebase_uid")
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
